spring.application.name=netflix

# Thông tin kết nối
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Cấu hình JPA/Hibernate

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# # JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Cấu hình Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}
# Nếu Redis có password thì thêm dòng dưới, mặc định docker redis không có pass
# spring.data.redis.password=

# Port (Render yêu cầu)
server.port=${PORT:8080}

# Cấu hình Cache chung
spring.cache.type=redis
spring.cache.redis.time-to-live=600000 
# (600000ms = 10 phút, cache sẽ hết hạn sau 10p)


spring.data.redis.timeout=60000

spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=1


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB